### ISSUE TITLE
SNS_SetPlaylist not working since Sonos update

### ISSUE THREAD

**Issue by severinbraun** [tkugelberg/SymconSonos#13]
Since the last Sonos update the function SNS_SetPlaylist is not working anymore.

When sending this request:

```php
SNS_SetPlaylist(37757,"1LIVE");
``` 

I get the following error

```
Fatal error: Uncaught Exception: Error during Soap Call: UPnPError s:Client 800 (UNKNOWN) in /var/lib/symcon/modules/.store/de.kugelberg.sonos/libs/sonosAccess.php:801
Stack trace:
#0 /var/lib/symcon/modules/.store/de.kugelberg.sonos/libs/sonosAccess.php(26): SonosAccess->processSoapCall('/MediaRenderer/...', 'urn:schemas-upn...', 'AddURIToQueue', Array)
#1 /var/lib/symcon/modules/.store/de.kugelberg.sonos/SonosPlayer/module.php(2005): SonosAccess->AddToQueue('x-sonosapi-stre...', '<DIDL-Lite xmln...')
#2 /var/lib/symcon/scripts/__generated.inc.php(1127): SonosPlayer->SetPlaylist('1LIVE')
#3 /var/lib/symcon/scripts/50385.ips.php(3): SNS_SetPlaylist(37757, '1LIVE')
#4 {main}
  thrown in /var/lib/symcon/modules/.store/de.kugelberg.sonos/libs/sonosAccess.php on line 801
``` 

Would be happy if anyone could fix that in the module.

**Comment by tkugelberg** [comment]
Hi,

SymconSonos this is outdated.
Please use https://github.com/tkugelberg/Sonos instead.

I have just tested setting Playlists, without any issues.

Regards,
     Thorsten
